version: 0.2

env:
  parameter-store:
    GOOGLE_API_KEY: /CodeBuild/GOOGLE_API_KEY

phases:
  install:
      runtime-versions:
        nodejs: 10
  build:
    commands:
       - yarn install
       - yarn data #temporary
       - yarn run generate

artifacts:    
  files:
    - '**/*'
  base-directory: dist